### PR TITLE
New `v4list` API with SSO token support

### PR DESCRIPTION
**Pull request by constcrist**
See documentation here:
https://github.com/intuitivelabs/intuitive-issues/wiki/whitelist-API
https://github.com/intuitivelabs/intuitive-issues/wiki/whitelist-API#v4list

also see here for a description on how to use it and test it:
https://github.com/intuitivelabs/intuitive-issues/issues/255

### CODE REVIEW

**Comment by constcrist** [comment]
### tests

1. no token (the API client gets an empty answer from the server)
config:
```
#TOKEN="z0FfTU8ibFBKYmWhLmQ8uPuHaYn327unSGuAWwG8Ep37Q12cZ252cLBvF71GNRfE"
LKID="0"
#VERSION=2
URL="https://i06.d.intuitivelabs.com/api/"
CHAIN="BLOCKER"
INTERVAL="60s"
FULL="yes"
BLACKLIST_TTL="24h"
STATE_FILENAME="/tmp/apiban.state"
ENCRYPTION_KEY="bb8dcd7be9a6f43b3304c640d7d7103c"
```
log
```
2021/04/06 20:28:38 ** Started APIBAN IPSETS CLIENT
2021/04/06 20:28:38 Licensed under GPLv2. See LICENSE for details.
loading config file "apiban-ipsets/config_integration_token.ini" ...
2021/04/06 20:28:38 FULL=yes in config file, resetting LKID
2021/04/06 20:28:38 LKID:0
2021/04/06 20:28:38 Chain:BLOCKER
2021/04/06 20:28:38 Interval for checking the list:1m0s
Creating ipset...
2021/04/06 20:28:38 create chain "BLOCKER" in table "filter"
2021/04/06 20:28:38 exec: "iptables -t filter -N BLOCKER || iptables -t filter -F BLOCKER"
2021/04/06 20:28:38 Adding chain "BLOCKER" as target to table:"filter" chain:"INPUT"
2021/04/06 20:28:38 exec: "iptables -t filter -I INPUT 1 -j BLOCKER"
2021/04/06 20:28:38 Adding chain "BLOCKER" as target to table:"filter" chain:"FORWARD"
2021/04/06 20:28:38 exec: "iptables -t filter -I FORWARD 1 -j BLOCKER"
2021/04/06 20:28:38 exec: "ipset create blacklist hash:ip family inet hashsize 1024 maxelem 65536 timeout 0 -exist"
2021/04/06 20:28:38 exec: "iptables -t filter -I BLOCKER 1 -m set --match-set blacklist src -j DROP"
2021/04/06 20:28:38 exec: "ipset create whitelist hash:ip family inet hashsize 1024 maxelem 65536 timeout 0 -exist"
2021/04/06 20:28:38 exec: "iptables -t filter -I BLOCKER 1 -m set --match-set whitelist src -j ACCEPT"
going to run in a looop
URL https://i06.d.intuitivelabs.com/api/
TICK1m0s2021/04/06 20:28:38 ticker:  2021-04-06 20:28:38.865450485 +0200 CEST m=+0.059808599
2021/04/06 20:28:38 ticker: 2021-04-06 20:28:38.865454253 +0200 CEST m=+0.059812366
2021/04/06 20:28:38 "bwnoa/v4list" api url: https://i06.d.intuitivelabs.com/api/bwnoa/v4list?list=ipblack&timestamp=0
2021/04/06 20:28:39 JSON response: &{map[]  []}
2021/04/06 20:28:39 No new bans to add...
2021/04/06 20:28:39 ttl: 86400
2021/04/06 20:28:39 "bwnoa/v4list" api url: https://i06.d.intuitivelabs.com/api/bwnoa/v4list?list=ipwhite&timestamp=0
2021/04/06 20:28:39 JSON response: &{map[]  []}
2021/04/06 20:28:39 No new bans to add...
2021/04/06 20:28:39 ttl: 86400
2021/04/06 20:28:39 ticker:  2021-04-06 20:28:39.314783894 +0200 CEST m=+0.509142002
...
```

```
root@firiel:/home/cco/go/src/github.com/intuitivelabs/apiban/clients/go# ipset -L
Name: blacklist
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 0
Size in memory: 200
References: 1
Number of entries: 0
Members:

Name: whitelist
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 0
Size in memory: 200
References: 1
Number of entries: 0
Members:
```

2. with token; see here for how to get a valid SSO token:
https://github.com/intuitivelabs/intuitive-issues/issues/255#issuecomment-813360724
config:
```
TOKEN="z0FfTU8ibFBKYmWhLmQ8uPuHaYn327unSGuAWwG8Ep37Q12cZ252cLBvF71GNRfE"
LKID="0"
#VERSION=2
URL="https://i06.d.intuitivelabs.com/api/"
CHAIN="BLOCKER"
INTERVAL="60s"
FULL="yes"
BLACKLIST_TTL="24h"
STATE_FILENAME="/tmp/apiban.state"
ENCRYPTION_KEY="bb8dcd7be9a6f43b3304c640d7d7103c"
```

logs:

```
URL https://i06.d.intuitivelabs.com/api/
TICK1m0s2021/04/06 20:33:19 ticker:  2021-04-06 20:33:19.024874194 +0200 CEST m=+0.051656399
2021/04/06 20:33:19 ticker: 2021-04-06 20:33:19.024888488 +0200 CEST m=+0.051670700
2021/04/06 20:33:19 "bwnoa/v4list" api url: https://i06.d.intuitivelabs.com/api/bwnoa/v4list?list=ipblack&timestamp=0&token=z0FfTU8ibFBKYmWhLmQ8uPuHaYn327unSGuAWwG8Ep37Q12cZ252cLBvF71GNRfE
2021/04/06 20:33:19 JSON response: &{map[ApiParameters:map[list:ipblack timestamp:0 token:z0FfTU8ibFBKYmWhLmQ8uPuHaYn327unSGuAWwG8Ep37Q12cZ252cLBvF71GNRfE] Count:19 Generatedat:1.617733999e+09 Generatedby:IntuitiveLabs ScannedCount:19 defaultBlacklistTtl:172800 dynamoParams:map[ExpressionAttributeNames:map[#did:domain #ts:timestamp] ExpressionAttributeValues:map[:div:3eb411b5-b749-4ca4-9c85-8f3d911c1c96#ipblack :start_ts:0] IndexName:i06data-ipblacklistgsi KeyConditionExpression:#did = :div AND #ts > :start_ts TableName:i06data-IPBlacklist-1R1E891VYUUJ2] endnote:no more items lastTimestamp:1.617733814e+09]  [{plain 45.134.144.26} {plain 51.15.146.240} {plain 51.15.157.120} {plain 217.182.235.12} {plain 162.142.125.149} {plain 178.32.196.220} {plain 190.202.144.251} {plain 193.107.216.13} {plain 207.244.225.82} {plain 151.106.39.204} {plain 162.142.125.56} {plain 193.107.216.78} {plain 45.134.144.100} {plain 162.142.125.155} {plain 104.140.188.46} {plain 193.46.255.63} {plain 193.107.216.125} {plain 45.134.144.22} {plain 151.106.41.42}]}
2021/04/06 20:33:19 e.ID empty
2021/04/06 20:33:19 ttl: 86400
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 45.134.144.26
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 51.15.146.240
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 51.15.157.120
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 217.182.235.12
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 162.142.125.149
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 178.32.196.220
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 190.202.144.251
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 193.107.216.13
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 207.244.225.82
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 151.106.39.204
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 162.142.125.56
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 193.107.216.78
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 45.134.144.100
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 162.142.125.155
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 104.140.188.46
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 193.46.255.63
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 193.107.216.125
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 45.134.144.22
2021/04/06 20:33:19 encrypt field: plain
2021/04/06 20:33:19 processed IP: 151.106.41.42
2021/04/06 20:33:19 "bwnoa/v4list" api url: https://i06.d.intuitivelabs.com/api/bwnoa/v4list?list=ipwhite&timestamp=0&token=z0FfTU8ibFBKYmWhLmQ8uPuHaYn327unSGuAWwG8Ep37Q12cZ252cLBvF71GNRfE
2021/04/06 20:33:19 JSON response: &{map[ApiParameters:map[list:ipwhite timestamp:0 token:z0FfTU8ibFBKYmWhLmQ8uPuHaYn327unSGuAWwG8Ep37Q12cZ252cLBvF71GNRfE] Count:0 Generatedat:1.617733999e+09 Generatedby:IntuitiveLabs ScannedCount:0 defaultBlacklistTtl:172800 dynamoParams:map[ExpressionAttributeNames:map[#did:domain #ts:timestamp] ExpressionAttributeValues:map[:div:3eb411b5-b749-4ca4-9c85-8f3d911c1c96#ipwhite :start_ts:0] IndexName:i06data-ipblacklistgsi KeyConditionExpression:#did = :div AND #ts > :start_ts TableName:i06data-IPBlacklist-1R1E891VYUUJ2] endnote:no more items lastTimestamp:0]  []}
2021/04/06 20:33:19 No new bans to add...
2021/04/06 20:33:19 ttl: 86400
2021/04/06 20:33:19 ticker:  2021-04-06 20:33:19.754475311 +0200 CEST m=+0.781257508
...
```
```
root@firiel:/home/cco/go/src/github.com/intuitivelabs/apiban/clients/go# ipset -L blacklist
Name: blacklist
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 0
Size in memory: 2024
References: 1
Number of entries: 19
Members:
207.244.225.82 timeout 86361
190.202.144.251 timeout 86361
193.107.216.78 timeout 86361
45.134.144.22 timeout 86361
162.142.125.155 timeout 86361
51.15.146.240 timeout 86361
45.134.144.100 timeout 86361
151.106.39.204 timeout 86361
178.32.196.220 timeout 86361
104.140.188.46 timeout 86361
162.142.125.149 timeout 86361
151.106.41.42 timeout 86361
193.46.255.63 timeout 86361
45.134.144.26 timeout 86361
217.182.235.12 timeout 86361
51.15.157.120 timeout 86361
162.142.125.56 timeout 86361
193.107.216.13 timeout 86361
193.107.216.125 timeout 86361
```

**Comment by jiriatipteldotorg** [comment]
Not sure if I read this code correctly, so forgive my possible ignorance -- just in the token-less case -- it may be worth checking for specific negative answers rather than ignoring absence of valid answer elements.  A negative answer is JSON and always includes elements like this: `{"statusCode":403,"statusDescription":"no admin level in bwapi call v4list"}` See also https://github.com/intuitivelabs/intuitive-issues/wiki/whitelist-API

**Comment by constcrist** [comment]
> Not sure if I read this code correctly, so forgive my possible ignorance -- just in the token-less case -- it may be worth checking for specific negative answers rather than ignoring absence of valid answer elements. A negative answer is JSON and always includes elements like this: `{"statusCode":403,"statusDescription":"no admin level in bwapi call v4list"}` See also https://github.com/intuitivelabs/intuitive-issues/wiki/whitelist-API

the current implementation (due to the _huge technical debts_ inherited from apiban) deals with the token-less case in the following way:

1. the HTTP response body cannot be parsed into the one expected for IP bl/wl;
2. due to 1 and the way the json parser is implemented in golang, either the bl or the wl got from the response are _empty_:
```
2021/04/07 13:50:38 ticker: 2021-04-07 13:50:38.580401174 +0200 CEST m=+0.055481423
2021/04/07 13:50:38 "bwnoa/v4list" api url: https://i06.d.intuitivelabs.com/api/bwnoa/v4list?list=ipblack&timestamp=0
2021/04/07 13:50:38 JSON response: &{map[]  []}
2021/04/07 13:50:38 No new bans to add...
2021/04/07 13:50:38 ttl: 86400
2021/04/07 13:50:38 "bwnoa/v4list" api url: https://i06.d.intuitivelabs.com/api/bwnoa/v4list?list=ipwhite&timestamp=0
2021/04/07 13:50:39 JSON response: &{map[]  []}
2021/04/07 13:50:39 No new bans to add...
2021/04/07 13:50:39 ttl: 86400
2021/04/07 13:50:39 ticker:  2021-04-07 13:50:39.100657889 +0200 CEST m=+0.575738129
```
```
root@firiel:/home/cco/go/src/github.com/intuitivelabs/apiban/clients/go# ipset -L
Name: blacklist
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 0
Size in memory: 200
References: 1
Number of entries: 0
Members:

Name: whitelist
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 0
Size in memory: 200
References: 1
Number of entries: 0
Members:
```

now:
1. either we agree with this behaviour for the timebeing
2. or we implement parsing more types of JSON answers (e.g. token auth. error) and we signal the user that there was some error in processing the request on the server...

**Comment by constcrist** [comment]
https://github.com/intuitivelabs/intuitive-issues/milestone/1

**Pull request merged**
